main_repo: "https://code.videolan.org/videolan/libplacebo.git"
homepage: "https://libplacebo.org/"
language: c
primary_contact: "spenwuwu@gmail.com"
auto_ccs:
  - "spenwuwu@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
